title: Semánticas
description: "Letras y delirios posthumanos"
author:
  name: "Alberto R. León"
  email: "hola@mrleon.space"
  url: "https://mrleon.space"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Alberto R. León"
year : "2020"
